### ISSUE TITLE
small issue about rect.

### ISSUE THREAD

**Issue by CT-7567-C-REX** [CT-7567-C-REX/GradProject#16]
<img width="314" alt="Screenshot 2024-12-19 at 03 48 09" src="https://github.com/user-attachments/assets/6f82405f-2811-4a9e-89a7-54fcefd45237" />
this variable not used anymore.
but Initialize rect tool depend on it so adjust the rect tool and remove this variable.
this is very small issue so directly push into main

**Comment by plentruel** [comment]
Solved.
