### ISSUE TITLE
bbox update

### ISSUE THREAD

**Issue by CT-7567-C-REX** [CT-7567-C-REX/GradProject#20]
bbow should return these:

top left x, y 
and height, width

you can test it from[here](https://yolo-mark-pwa.github.io)

**Comment by plentruel** [comment]
Solved.

**Comment by CT-7567-C-REX** [comment]
this is not done yet

**Comment by plentruel** [comment]
![resim_2024-12-21_073206121](https://github.com/user-attachments/assets/9839baaa-53c6-452d-ba8c-d1533629b8cd)
This does it.

**Comment by plentruel** [comment]
Solved

**Comment by plentruel** [comment]
Solved.
