### ISSUE TITLE
bbox shape

### ISSUE THREAD

**Issue by CT-7567-C-REX** [CT-7567-C-REX/GradProject#21]
change the shape of the bbox as fallow:

![six](https://github.com/user-attachments/assets/7916731d-45fc-437a-9cb2-d662bb1f769d)

add double rectangle with green color(it is not among the existing classes)

Taner hoca said you can chose the bbox colors, but when they chose same colors as the class they will be invisible, so this double rect is gonna used for that purpose.

**Comment by plentruel** [comment]
Solved.
