### ISSUE TITLE
Bounding Box Scales with Canvas Zoom

### ISSUE THREAD

**Issue by CT-7567-C-REX** [CT-7567-C-REX/GradProject#23]
When zooming into the canvas the bounding boxes scale proportionally with the zoom level.

<img width="400" alt="Screenshot 2024-12-21 at 01 23 55" src="https://github.com/user-attachments/assets/d2220f60-03df-4482-bee9-350a2a11d9ca" />

The bounding boxes should remain at a consistent size relative to the viewport

**Comment by plentruel** [comment]
Solved.
