### ISSUE TITLE
bbox zoom pan button

### ISSUE THREAD

**Issue by CT-7567-C-REX** [CT-7567-C-REX/GradProject#24]
when draw rect button pressed make zoom/pan mode false so user can not pan the image while drawing a bbox

also apply same logic for the zoom pan btn. when pressed make draw rect false so user not drawing while paning the image

also add bootstrap disabled property to the zoom in/out buttons when it is not active:

<img width="400" alt="Screenshot 2024-12-21 at 01 50 41" src="https://github.com/user-attachments/assets/ec5df874-ebf0-47c9-900c-f76d66f21970" />

[doc for bootstrap](https://getbootstrap.com/docs/5.3/components/buttons/)

**Comment by plentruel** [comment]
Solved.
