### ISSUE TITLE
printing the rect datas at the endpoint

### ISSUE THREAD

**Issue by CT-7567-C-REX** [CT-7567-C-REX/GradProject#26]
so far I'm sending the images to the backend, and showing them wiht PIL.show()

I could't understand the structure of the recttool class so I'm unable to print the datas at the console.

at the scriptjs I use saveCanvasButton.onclick inside I call a function called 
createPayloadForBackEnd(fileInput, predimage, rectangleTool); this function defined inside utilsjs

inside that function pls modify the rect part so that is correctly including the top left xy height width inside the json data

and then print rect at the console at the flask side

**Comment by plentruel** [comment]
I made some adjustments, but printing in the console doesnt work because /rlhfprocess in app.py is overridden by another route or handdler. I reviewed the code base but couldn't find the issue. You might be having the same problem for this reason.

**Comment by plentruel** [comment]
Solved.
