### ISSUE TITLE
bbox label btns

### ISSUE THREAD

**Issue by CT-7567-C-REX** [CT-7567-C-REX/GradProject#29]
add 5 buttons to the front end for each class:

<img width="400" alt="Screenshot 2024-12-25 at 20 13 01" src="https://github.com/user-attachments/assets/4dfff2aa-ab18-4468-8f02-97f6fed3cd2f" />

these will be used for assigning labels for the bboxes.

example: when user chose white(background) label should be "(255,255,255)"
this will be used for loss. data type can be string np.
use bootstrap buttons for ease. fallow the same structure for buttons that we had so far.
place the new btns inside a div at rlhf thml page.
make the 5 new button same color as their classes.

**Comment by plentruel** [comment]
On it.

**Comment by plentruel** [comment]
Solved.

**Comment by CT-7567-C-REX** [comment]
add the same classes as color maps.

<img width="300" alt="Screenshot 2024-12-26 at 23 28 22" src="https://github.com/user-attachments/assets/856d0d39-4548-48aa-a340-93478b60c16b" />

if same colors as this one is not found then the loss function throw an error
right now the new buttons only works with white button.
update the class names also, instead of color names.
also put a tick or something to indicate the button has been selected _(this is optional but would be good)_

**Comment by CT-7567-C-REX** [comment]
<img width="400" alt="Screenshot 2024-12-26 at 23 39 34" src="https://github.com/user-attachments/assets/e1012e25-7b3c-4013-9938-e46b11e943d9" />

can this part moved to canvas_utils or canvas js?

the script js is getting crowded and hard to understand. thats why we divided into files.
when considered canvas button reference works at canvas js I think this structure can also be moved away from script js file?
