### ISSUE TITLE
draw a bounding box

### ISSUE THREAD

**Issue by CT-7567-C-REX** [CT-7567-C-REX/GradProject#5]
https://stackoverflow.com/a/45917491/21275789

we need to add this functionality but more refined version.

we also save the boxes location data for later usage at the backend

**Comment by plentruel** [comment]
On it

**Comment by plentruel** [comment]
Functionality implemented. 

Next step: calculate edge coordinates for backend integration.

**Comment by plentruel** [comment]
Corner coordinates are calculated.
A prompt() asks for a label/description.
Coordinates and labels are stored in this.drawnRectangles for backend.
