### ISSUE TITLE
zoom out limit

### ISSUE THREAD

**Issue by CT-7567-C-REX** [CT-7567-C-REX/GradProject#9]
we can zoom out limitless:
<img width="1037" alt="Screenshot 2024-12-12 at 21 31 45" src="https://github.com/user-attachments/assets/e1726d08-b834-4a81-9caf-53e52ce4ced7" />

this needs to be limited with imige size itself.
actually there is a zoom out limit, I think it is half size of the image original size needs to be checked again.
also there is a limit for the zoom in, which is very low, it should be either very high so that we can zoom in in detail, or no limit.

and track pad movements(this is my opinion, is hard to control) needs to be removed or refined.

**Comment by plentruel** [comment]
Solved
